[package]
name = "metal-flash-attention"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "2.3.1"
metal = "0.26.0"
num-traits = "0.2.17"
rand = "0.8.5"
once_cell = "1.8.0"
